services:
  web:
    image: "${WEB_IMAGE}"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      TEST_ENV: test_env

x-uffizzi:
  ingress:
    service: web
    port: 80
  continuous_preview:
    share_to_github: true
    delete_preview_after: 48h
    delete_preview_when_pull_request_is_closed: true
    deploy_preview_when_pull_request_is_opened: true
